<?php declare(strict_types = 1);

namespace PHPStan\ExtensionInstaller;

/**
 * This class is generated by phpstan/extension-installer.
 * @internal
 */
final class GeneratedConfig
{

	public const EXTENSIONS = array (
  'phpstan/phpstan-webmozart-assert' => 
  array (
    'install_path' => 'C:\\xampp\\htdocs\\erp\\vendor/phpstan/phpstan-webmozart-assert',
    'relative_install_path' => '../../phpstan-webmozart-assert',
    'extra' => 
    array (
      'includes' => 
      array (
        0 => 'extension.neon',
      ),
    ),
    'version' => '1.2.4',
  ),
);

	public const NOT_INSTALLED = array (
);

	private function __construct()
	{
	}

}
